import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { Catalog } from "./catalog.js";
import type { Observation, ScholarReconciliation, ScholarRow } from "./types.js";
import { SCHEMA_VERSION } from "./types.js";
import { atomicWriteJson, normalizeText, now, uuid, withLock } from "./utils.js";
import { MyPubError } from "./errors.js";

function split(line: string): string[] { const result: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < line.length; index++) { const char = line[index]!; if (char === '"') { if (quoted && line[index + 1] === '"') { value += '"'; index++; } else quoted = !quoted; } else if (char === "," && !quoted) { result.push(value); value = ""; } else value += char; } result.push(value); return result; }

export async function importScholarSnapshot(catalog: Catalog, path: string, completeness: Observation["completeness"] = "complete", defaultObservedAt = now()): Promise<ScholarReconciliation> {
  const lines = (await readFile(path, "utf8")).replace(/^\uFEFF/, "").split(/\r?\n/).filter((line) => line.trim()); if (lines.length < 2) throw new MyPubError("Scholar CSV is empty", "IMPORT_INVALID"); const headers = split(lines[0]!).map((header) => normalizeText(header).replace(/ /g, "_")); const publications = await catalog.list({ includeArchived: true });
  const rows: ScholarRow[] = lines.slice(1).map((line, index) => { const values = split(line); const get = (...names: string[]): string | undefined => { for (const name of names) { const position = headers.indexOf(name); if (position >= 0 && values[position]?.trim()) return values[position]!.trim(); } return undefined; }; const title = get("title"); if (!title) throw new MyPubError(`Scholar CSV row ${index + 2} has no title`, "IMPORT_INVALID"); const yearText = get("year"); const countText = get("citation_count", "citations", "cited_by"); const scholarId = get("scholar_id", "article_id"); const url = get("article_url", "url"); const observedAt = get("observed_at", "observation_time") ?? defaultObservedAt; const idMatches = scholarId ? publications.filter((publication) => publication.urls.some((item) => item.includes(scholarId))) : []; const titleMatches = publications.filter((publication) => normalizeText(publication.title) === normalizeText(title) && (!yearText || Object.values(publication.dates).some((date) => date?.startsWith(yearText)))); const matches = idMatches.length ? idMatches : titleMatches; return { title, ...(yearText ? { year: Number(yearText) } : {}), ...(get("venue") ? { venue: get("venue")! } : {}), ...(scholarId ? { scholar_id: scholarId } : {}), ...(url ? { article_url: url } : {}), ...(countText !== undefined && countText !== "" ? { citation_count: Number(countText) } : {}), observed_at: observedAt, matched_publication_ids: matches.map((publication) => publication.id), match: idMatches.length === 1 ? "exact-id" : matches.length === 1 ? "title-year" : matches.length > 1 ? "ambiguous" : "unmatched" }; });
  if (rows.some((row) => row.citation_count !== undefined && (!Number.isInteger(row.citation_count) || row.citation_count < 0))) throw new MyPubError("Citation counts must be non-negative integers or blank (unknown)", "IMPORT_INVALID");
  const observationId = uuid(); const observedAt = rows.map((row) => row.observed_at).sort().at(-1) ?? defaultObservedAt; const observation: Observation = { schema_version: SCHEMA_VERSION, id: observationId, kind: "citation", provider: "google-scholar", publication_ids: [...new Set(rows.flatMap((row) => row.matched_publication_ids))], observed_at: observedAt, source: path, payload: { rows }, completeness, parser_version: "mypub-scholar-csv/1" };
  await withLock(join(catalog.localDir, "write.lock"), () => atomicWriteJson(join(catalog.observationsDir, `${observationId}.json`), observation));
  const matchedIds = new Set(observation.publication_ids); const differences: ScholarReconciliation["differences"] = [];
  for (const row of rows.filter((item) => item.matched_publication_ids.length === 1)) { const publication = publications.find((item) => item.id === row.matched_publication_ids[0])!; if (publication.title !== row.title) differences.push({ publication_id: publication.id, field: "title", local: publication.title, observed: row.title }); const localYear = (publication.dates.issued ?? publication.dates.online ?? publication.dates.submitted ?? "").slice(0, 4); if (row.year && localYear && localYear !== String(row.year)) differences.push({ publication_id: publication.id, field: "year", local: localYear, observed: String(row.year) }); if (row.venue && publication.venue && normalizeText(row.venue) !== normalizeText(publication.venue)) differences.push({ publication_id: publication.id, field: "venue", local: publication.venue, observed: row.venue }); }
  const groups = new Map<string, ScholarRow[]>(); for (const row of rows) if (row.scholar_id) groups.set(row.scholar_id, [...(groups.get(row.scholar_id) ?? []), row]);
  return { observation_id: observationId, observed_at: observedAt, completeness, local_only: completeness === "complete" ? publications.filter((item) => !matchedIds.has(item.id)).map((item) => item.id) : [], source_only: rows.filter((row) => row.match === "unmatched"), matched: rows.filter((row) => row.match === "exact-id" || row.match === "title-year"), ambiguous: rows.filter((row) => row.match === "ambiguous"), differences, shared_counts: [...groups.entries()].flatMap(([scholar_id, grouped]) => { const publication_ids = [...new Set(grouped.flatMap((row) => row.matched_publication_ids))]; return publication_ids.length > 1 ? [{ scholar_id, publication_ids, ...(grouped[0]?.citation_count !== undefined ? { citation_count: grouped[0].citation_count } : {}) }] : []; }) };
}
